[ai]
gemini_api_key = "AIzaSyBKRTBFXIReKPLwglrCDsxU5MwYg1Tr0T8"

[smtp]
user = "saam678a@gmail.com"
password = "ksbv fbqz prkg ztmk"
host = "smtp.gmail.com"
port = 587
recipient = "alejandro.adam@hgt.com"

[jefatura]
password = "hgt2025"
email    = "alejandro.adam@hgt.com"